version: "3.3"
services:
    nodeserer:
      container_name: webapp
      build:
          context: ./web
      ports:
          # - "8000:8000"
          - "127.0.0.1:8000:8000"
      depends_on:
          - mongo
    mongo:
      container_name: mongodb
      build:
          context: ./mongo
      # image: mongo
      ports:
          - "27017:27017"

